# Generated by Django 6.0.1 on 2026-01-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_chamado_atribuido_a_alter_chamado_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='BAIXA', max_length=10),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Em andamento'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20),
        ),
    ]
