# Generated by Django 6.0.1 on 2026-01-19 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_chamado_data_limite_alter_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ANDAMENTO', 'Em andamento'), ('SOLUCIONADO', 'Solucionado'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=20),
        ),
    ]
